WIP Updates to the 'Importing modules into Pantheon' module
redhataccess/pantheon pull request #450
Opened 2020-10-25 14:11 UTC by RichardHoch

Resolves https://projects.engineering.redhat.com/browse/FCCEUD-47

2020-10-25 14:12 UTC, RichardHoch commented
@redhataccess/pantheon-developers Please review for technical completeness and accuracy.

2020-10-27 15:42 UTC, benradey commented
@RichardHoch What you have here looks great - I might consider adding a blurb about the sync happening in the background - so just because you are immediately redirected in the UI, doesn't mean that all your files will be immediately available. Up to you if you think that is worth including.

2020-11-04 13:00 UTC, RichardHoch commented
@benradey -- please give the last paragraph ("Note that...")  a quick lookover before I ask for peer review. Thanks.

2020-11-13 16:12 UTC, benradey commented
@RichardHoch My apologies for keeping you waiting, but the update looks perfect to me - thanks!

2020-11-15 12:58 UTC, stoobie requested changes
Two comments, otherwise looks good!

2020-11-15 12:58 UTC, stoobie commented on pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc_importing-content.adoc
> +. By default, this procedure imports the "master" branch of the {ContentTerm} repository, but you can enter a specific branch to import instead if you prefer.
I don't understand this line. How do you import master? How do you import a branch?

2020-11-15 12:58 UTC, stoobie commented on pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/proc_importing-content.adoc
> +Note that it takes {ProductShortName} some time to synchronize its database and the UI following the import. Therefore your files may not be immediately available when you are redirected in the UI,
```suggestion
Note that {ProductShortName} takes time to synchronize its database and the GUI following the import. Therefore your files might not be immediately available when you are redirected in the GUI,
```
Looking for more brevity. Also, don't use "may", it's ambiguous.

2020-12-09 09:28 UTC, stoobie approved these changes
LGTM

2020-12-09 09:44 UTC, stoobie commented
@benradey or @redhataccess/pantheon-developers This PR is ready to be merged.

2020-12-22 15:51 UTC, RichardHoch commented
@benradey or @redhataccess/pantheon-developers -- please merge this PR.

2021-01-05 14:09 UTC, benradey approved these changes

2021-01-05 14:09 UTC, merged