WIP con_about-assemblies
redhataccess/pantheon pull request #517
Opened 2021-02-22 09:48 UTC by RichardHoch

2021-02-22 09:49 UTC, RichardHoch commented
@redhataccess/pantheon-developers Please review for technical completeness and accuracy.

2021-02-22 16:49 UTC, benradey commented
From a tech perspective, this looks perfect. Tech review complete.

Cosmetically, I noticed a typo ("assemply") on line 11.

2021-02-23 07:54 UTC, RichardHoch commented
@benradey -- thanks. Typo fixed.

2021-03-04 16:15 UTC, stoobie requested changes

2021-03-04 16:15 UTC, stoobie commented on pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/con_about-assemblies.adoc
> +In {ProductName} {ProdctNumber}, each assembly encompasses a single user story. An assembly can include concept, procedure, or reference modules but all modules in an assembly must relate to that spe
@RichardHoch 

```{ProductNumber}```

2021-03-04 16:15 UTC, stoobie commented on pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/con_about-assemblies.adoc
> +In {ProductName} {ProdctNumber}, each assembly encompasses a single user story. An assembly can include concept, procedure, or reference modules but all modules in an assembly must relate to that spe
1. There are "Guides" in Pantheon 2, which are based on user stories.
2. "...with one assembly per user story."
What about nested assemblies? They will eventually be supported. See https://redhat-documentation.github.io/modular-docs/#what-modular-documentation-is.
3. "This change is part of our efforts to make it easier for users to search for each specific action they want to perform."
Suggestion: "Focusing on user stories is part of the Flexible Customer Content (FCC) effort at Red Hat. One of the goals of this approach is to make it easier..."

2021-03-04 16:15 UTC, stoobie commented on pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/con_about-assemblies.adoc
>  Link:https://redhat-documentation.github.io/modular-docs/#forming-assemblies[Assemblies] are discussed in detail in our company's description of modular documentation. Here are specific guidelines fo
I suggest putting this under .Additional resources, which is compatible with the mod docs guidelines.

2021-03-04 16:27 UTC, stoobie commented
@RichardHoch I think that we need to mention somewhere that nested assemblies are not currently supported in this version of Pantheon 2, but that they will be in the future. I added a note to this effect in the Jira item.

2021-03-16 07:48 UTC, stoobie requested changes

2021-03-16 07:48 UTC, stoobie commented on pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/con_about-assemblies.adoc
> += About Assemblies
@RichardHoch Andrew pointed out that we agreed on the convention "Overview of..." so this would be "Overview of Assemblies"

2021-03-16 07:48 UTC, stoobie commented on pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/con_about-assemblies.adoc
> +
```suggestion
:_module-type: CONCEPT
```

2021-04-04 14:21 UTC, RichardHoch commented
@stoobie Made the changes you suggested and a few more; please review.

2021-04-07 13:05 UTC, stoobie requested changes

2021-04-07 13:05 UTC, stoobie commented on pantheon-bundle/src/main/resources/SLING-INF/content/docs/modules/con_about-assemblies.adoc
> +In {ProductName} {ProdctNumber}, each assembly encompasses a single user story. Previously, an assembly could include multiple user stories, with only one assembly being used for a complete user guid
@RichardHoch Sometimes a user story (assembly) requires other user stories. The Mod docs reference guide shows an example of this. So I don't know if this is completely accurate.

2021-04-11 12:00 UTC, RichardHoch commented
@stoobie: I made the changes we discussed. Please review.

2021-04-14 09:56 UTC, stoobie approved these changes
LGTM

2021-04-18 07:29 UTC, RichardHoch commented
@redhataccess/pantheon-developers -- please review for merge.

2021-04-19 09:21 UTC, stoobie commented
@anarang @benradey Can either of you merge this?

2021-04-19 09:22 UTC, stoobie approved these changes
LGTM. Approved.

2021-04-20 12:10 UTC, stoobie commented
@redhataccess/pantheon-developers Please merge.

2021-04-20 13:25 UTC, anarang approved these changes

2021-04-20 13:25 UTC, merged

2021-04-20 13:26 UTC, anarang commented
> @anarang @benradey Can either of you merge this?

@stoobie done, thanks.